### ISSUE TITLE
How to set the iOS identifier

### ISSUE THREAD

**Issue by wind13** [seantempesta/re-natal#2]
I try the `react-native run-ios`, and got this error:

```
Unexpected identifier 'GET'

customEval
figwheel-bridge.js:75
```

But the `react-native run-android` works ok.

So I think it is because of the iOS identifier setting. How to set it?

**Comment by seantempesta** [comment]
Hey @wind13.  This was just a fork of the re-natal project for a patch I made.  This branch is not maintained.  You should check out the main project for future reference.

https://github.com/drapanjanas/re-natal
